import { Montserrat, Mulish, Ubuntu } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { CustomScrollbar } from "@/components/custom-scrollbar";
import { ThemeProvider } from "next-themes";

const montserrat = Montserrat({
  variable: "--font-montserrat", // hanya untuk class tertentu
  subsets: ["latin"],
});

const nunito = Mulish({
  variable: "--font-nunito",     // digunakan sebagai default
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "People Impact",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>People Impact</title>
        <meta name="description" content="Your Swift Reliable Solutions" />
      </head>
      <body
        className={`${nunito.className} ${montserrat.variable}  antialiased`}
      >
        <ThemeProvider enableSystem attribute={'class'}>
          <Navbar />
          {children}
          <CustomScrollbar /> 
        </ThemeProvider>
      </body>
    </html>
  );
}
